### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by rchadgray** [calebsurface/ProPresenter-OBS#3]
I have ProPresenter on a mac computer and i am running your code on a PC computer.

I have the firewall turned off on the mac.

I get this in the developer tools of my chrome browser.
WebSocket connection to 'ws://10.1.0.92:55/stagedisplay' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Can this code work over a network or does it have to be on the same computer that ProPresenter is on?

Thanks!

Edit... i am not sure if this matters, but i am running a demo version of ProPresenter.  Also i cannot get the code to connect running on the same computer as ProPresenter.

**Comment by calebsurface** [comment]
Eric, sorry for the late reply!

My personal use-case is using this over the network. I have it running on two completely separate machines. I do not know if the demo version of ProPresenter makes a difference here. Have you checked in the preferences to make sure everything there is enabled for "Network"?

**Comment by rchadgray** [comment]
Let me get back into this code and i will test again.  You have this running on PP version 6?

Thanks for the reply!  I will test again.

**Comment by rchadgray** [comment]
Oh, i think i was using the wrong port number.  I was using the port down in Enable Stage Display App.  (55).  I put in the port listed on the "enable network" and now i seem to be getting data.

![image](https://user-images.githubusercontent.com/1903834/50099179-78f86d80-01eb-11e9-91a0-d462e0219aed.png)

**Comment by calebsurface** [comment]
Yeah, the ports always confuse me, but eventually I get it working again.
