### ISSUE TITLE
Stop it from pulling the date?

### ISSUE THREAD

**Issue by ZooBuZZ** [calebsurface/ProPresenter-OBS#5]
Hi,

Sorry for the noob question as I am not even close to an expert in this area.  Thank you very much for the useful script.  I downloaded it and have it installed.  It is mostly working...however, I see the lyrics pop up in obs for about half a second and then it goes to the date.  Then it just just stays on the current date.  I thought maybe it was because I was showing the date in the stage display view, but even after turning that off the date still just comes up.  Has anyone experienced this?  Any thoughts?  Thanks!

Zach

**Comment by mwgustin** [comment]
I had this same issue - I just submitted a pull request that fixes it. Hopefully @calebsurface  is monitoring and can merge in the fix.  You can try my fork in the mean time.  https://github.com/mwgustin/ProPresenter-OBS

**Comment by calebsurface** [comment]
Hey @ZooBuZZ, sorry I didn't respond to this! I've merged the fix that @mwgustin added. Should be good to go! Thanks to you both.

**Comment by ZooBuZZ** [comment]
Sorry for the late response, but yes I have it working now.  Thanks!! @mwgustin @calebsurface
